add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$golang\
$rust\
$terraform\
$cmd_duration\
$line_break\
$character
"""

[directory]
style = "blue bold"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "purple bold"

[git_status]
style = "red bold"

[nodejs]
symbol = "⬢ "
format = "[$symbol($version )]($style)"
style = "green"

[python]
symbol = "🐍 "
format = "[$symbol($version )]($style)"
style = "yellow"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"
style = "cyan"

[rust]
symbol = "🦀 "
format = "[$symbol($version )]($style)"
style = "red"

[terraform]
symbol = "💠 "
format = "[$symbol($version )]($style)"
style = "magenta"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "dimmed"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"